import {
  defaultCustomSettings,
  type Invitation,
} from "@/lib/invitation";

export const dummyInvitation: Invitation = {
  id: "preview",
  user_id: null,
  slug: "rina-pradipta",
  template_id: "elegant-classic",
  event_type: "Wedding",
  event_title: "Pernikahan Rina & Pradipta",
  groom_name: "I Wayan Pradipta Wibawa",
  bride_name: "Rina Maharani",
  groom_nickname: "Pradipta",
  bride_nickname: "Rina",
  groom_photo: "/example/couple-image.webp",
  bride_photo: "/example/couple-image-looking.webp",
  cover_image: "/example/couple-image-hug.webp",
  hero_title: "The Wedding of",
  hero_subtitle: "Dengan hormat kami mengundang Anda merayakan hari bahagia kami.",
  event_date: "2026-08-15",
  event_time: "16:00 WITA",
  venue_name: "Br. Lorem Ipsum, Bali",
  venue_address: "Br. Lorem Ipsum, Gianyar, Bali",
  google_maps_url: "https://maps.google.com/?q=Br.+Lorem+Ipsum+Bali",
  story_title: "Cerita Kami",
  story_content:
    "Kami bertemu di sebuah sore yang tenang di Ubud, saat kopi masih hangat dan percakapan terasa mudah.\n\nDari persahabatan yang sederhana, tumbuh keputusan untuk menempuh hidup bersama — dengan rasa syukur, keluarga, dan janji yang kami jaga.\n\nKini kami ingin berbagi sukacita itu bersama orang-orang yang kami kasihi.",
  music_url: null,
  gallery_images: [
    { id: "1", url: "/example/couple-image.webp", alt: "Lamaran", positionX: 50, positionY: 50, zoom: 100, rotate: 0 },
    { id: "2", url: "/example/couple-image-hug.webp", alt: "Prewedding", positionX: 50, positionY: 40, zoom: 100, rotate: 0 },
    { id: "3", url: "/example/couple-image-sit.webp", alt: "Keluarga", positionX: 50, positionY: 50, zoom: 100, rotate: 0 },
    { id: "4", url: "/example/couple-image-looking.webp", alt: "Potret", positionX: 50, positionY: 45, zoom: 100, rotate: 0 },
    { id: "5", url: "/example/couple-image.webp", alt: "Momen", positionX: 50, positionY: 50, zoom: 100, rotate: 0 },
  ],
  gift_accounts: [
    { id: "1", bank: "BCA", accountNumber: "1234567890", accountName: "Rina Maharani" },
    { id: "2", bank: "Mandiri", accountNumber: "9876543210", accountName: "I Wayan Pradipta Wibawa" },
  ],
  custom_settings: defaultCustomSettings(),
  groom_image_position_x: 50,
  groom_image_position_y: 50,
  groom_image_zoom: 100,
  groom_image_rotate: 0,
  is_published: true,
  created_at: new Date().toISOString(),
  updated_at: new Date().toISOString(),

  greeting_text: "Kepada Yth. Bapak/Ibu/Saudara/i",
  recipient_name: "Keluarga Besar Wimah",
  groom_parents: "Putra dari Bapak I Ketut Lorem Ipsum & Ibu Ni Nyoman Lorem Ipsum",
  bride_parents: "Putri dari Bapak H. Abdi Rahman Maharani & Ibu Hj. Dewi Lestari",
  groom_social: { instagram: "https://instagram.com/pradipta.wibawa" },
  bride_social: { instagram: "https://instagram.com/rina.maharani" },
  story_milestones: [
    {
      title: "Pertama Bertemu",
      date: "2021-03-15",
      description: "Kami pertama kali bertemu di sebuah kopi hangat di Ubud, saat langit sore mulai jingga.",
      image: "/example/couple-image.webp",
    },
    {
      title: "Pertemanan",
      date: "2021-06-20",
      description: "Dari obrolan ringan, kami mulai sering bertemu dan berbagi cerita tentang impian masing-masing.",
      image: "/example/couple-image-hug.webp",
    },
    {
      title: "Lamaran",
      date: "2025-12-25",
      description: "Di hari Natal yang penuh cinta, Pradipta melamar Rina di depan keluarga besar.",
      image: "/example/couple-image-sit.webp",
    },
    {
      title: "Hari Bahagia",
      date: "2026-08-15",
      description: "Kami akan mengucap janji suci di hadapan Tuhan dan orang-orang yang kami kasihi.",
      image: "/example/couple-image-looking.webp",
    },
  ],
  video_url: null,
  video_poster: null,
  rsvp_enabled: true,
  fun_facts: [
    { icon: "coffee", label: "Kopi Pertama", value: "Tahun 2021" },
    { icon: "heart", label: "Jalan Bareng", value: "4 Tahun" },
    { icon: "ring", label: "Lamaran", value: "25 Des 2025" },
    { icon: "calendar", label: "Hari Nikah", value: "15 Ags 2026" },
    { icon: "camera", label: "Foto Prewedding", value: "Bali" },
    { icon: "gift", label: "Cake Topper", value: "Custom" },
  ],
  closing_message: "Atas kehadiran dan doa restu Anda, kami mengucapkan terima kasih yang tulus. Semoga kebahagiaan selalu menyertai kita semua.",
  closing_image: "/example/couple-image-looking.webp",
  qris_image: null,
};
